import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Bell, Check, ChevronDown, Clock3, CloudRain, Gem, MapPin, Menu, Plus, Sparkles, Star, Umbrella, Users, X, Zap } from 'lucide-react';
import './styles.css';
import './maximalist.css';

const initialExperiences = [
  { id: 1, title: 'Alleyway Pottery Workshop', kind: 'Hands-on craft', distance: '0.8 km away', travel: '8 min walk', duration: '55 min', fit: 96, match: 98, image: 'https://images.unsplash.com/photo-1565193298357-c34c6fc9f03f?auto=format&fit=crop&w=900&q=80', pin: 'A', tone: 'violet' },
  { id: 2, title: 'Secret Espresso Bar', kind: 'Coffee & conversation', distance: '0.3 km away', travel: '4 min walk', duration: '35 min', fit: 94, match: 96, image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80', pin: 'B', tone: 'emerald' },
  { id: 3, title: 'Rooftop Stories at Old Mint', kind: 'Culture & heritage', distance: '1.1 km away', travel: '12 min walk', duration: '45 min', fit: 91, match: 94, image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=900&q=80', pin: 'C', tone: 'amber' },
  { id: 4, title: 'Vinyl Listening Room', kind: 'After-dark gem', distance: '0.6 km away', travel: '7 min walk', duration: '50 min', fit: 89, match: 92, image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80', pin: 'D', tone: 'rose' },
];
const rainExperiences = [
  { id: 5, title: 'Covered Artisan Market', kind: 'Indoor local makers', distance: '0.4 km away', travel: '5 min walk', duration: '50 min', fit: 98, match: 99, image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80', pin: 'A', tone: 'violet' },
  { id: 2, title: 'Secret Espresso Bar', kind: 'Coffee & conversation', distance: '0.3 km away', travel: '4 min walk', duration: '35 min', fit: 97, match: 96, image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80', pin: 'B', tone: 'emerald' },
  { id: 6, title: 'Underground Photo Archive', kind: 'Culture & heritage', distance: '0.7 km away', travel: '9 min walk', duration: '40 min', fit: 93, match: 95, image: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=900&q=80', pin: 'C', tone: 'amber' },
  { id: 4, title: 'Vinyl Listening Room', kind: 'After-dark gem', distance: '0.6 km away', travel: '7 min walk', duration: '50 min', fit: 92, match: 92, image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80', pin: 'D', tone: 'rose' },
];
const vibes = ['Solo & Quiet', 'Local Artisans', 'Hidden Food', 'Culture & Heritage', 'Nightlife'];

function App() {
  const [mode, setMode] = useState('traveler');
  const [hours, setHours] = useState(2.5);
  const [budget, setBudget] = useState('$$');
  const [chosenVibes, setChosenVibes] = useState(['Local Artisans', 'Culture & Heritage']);
  const [rain, setRain] = useState(false);
  const [showAlert, setShowAlert] = useState(false);
  const [itinerary, setItinerary] = useState([2, 1, 3]);
  const experiences = rain ? rainExperiences : initialExperiences;
  const itineraryItems = itinerary.map(id => experiences.find(x => x.id === id) || initialExperiences.find(x => x.id === id)).filter(Boolean);
  const totalMinutes = itineraryItems.reduce((total, item) => total + parseInt(item.duration) + parseInt(item.travel), 0);
  const toggleRain = () => { setRain(v => !v); setShowAlert(true); setTimeout(() => setShowAlert(false), 5000); };
  const addToItinerary = (id) => setItinerary(prev => prev.includes(id) ? prev : [...prev, id].slice(-3));
  const toggleVibe = vibe => setChosenVibes(prev => prev.includes(vibe) ? prev.filter(v => v !== vibe) : [...prev, vibe]);
  return <div className="app-shell">
    <div className="folk-pattern top-pattern"/><div className="folk-pattern side-pattern"/><div className="marigold marigold-one">✿</div><div className="marigold marigold-two">✿</div>
    <nav className="topbar">
      <div className="brand"><span className="gem"><Gem size={20}/></span><span>HiddenGems<span>AI</span></span></div>
      <div className="context"><MapPin size={14}/><span>Downtown Quarter</span><i/><span>☀ Clear 26°C</span></div>
      <div className="nav-actions"><button className="rain-button" onClick={toggleRain}><CloudRain size={16}/>{rain ? 'Restore original route' : 'Simulate rain / closure'}</button><button className="notification"><Bell size={18}/><b/></button><div className="mode-toggle"><button className={mode === 'traveler' ? 'active' : ''} onClick={() => setMode('traveler')}>Traveler</button><button className={mode === 'merchant' ? 'active' : ''} onClick={() => setMode('merchant')}>Merchant</button></div><button className="mobile-menu"><Menu/></button></div>
    </nav>
    {showAlert && <div className="weather-alert"><div className="alert-icon"><Umbrella size={21}/></div><div><strong>{rain ? 'Weather alert: Rain expected in 15 mins' : 'Route restored: Clear skies ahead'}</strong><p>{rain ? 'AI is replacing your outdoor walk with a nearby covered artisan market.' : 'Your original outdoor discoveries are back on the route.'}</p></div><button onClick={() => setShowAlert(false)}><X size={18}/></button></div>}
    {mode === 'traveler' ? <>
      <header className="hero"><div><p className="eyebrow"><Sparkles size={14}/> AI LOCAL CONCIERGE</p><h1>Your time is short.<br/><em>Make it unforgettable.</em></h1><p className="subtitle">We find the little places that turn a free afternoon into a story worth keeping.</p><div className="hand-painted-note">Made for happy wandering <span>✦</span></div></div><div className="hero-art" aria-hidden="true"><div className="hero-sun">☼</div><div className="hero-flower f-one">✿</div><div className="hero-flower f-two">❋</div><div className="hero-flower f-three">✽</div><p>Ghoomo<br/>Phiro</p></div><button className="generate"><Sparkles size={18}/> Generate my route <ArrowUpRight size={17}/></button></header>
      <section className="control-bar glass"><div className="time-control"><div className="control-label"><Clock3 size={16}/> Available time <b>{hours} hrs</b></div><input type="range" min="1" max="8" step="0.5" value={hours} onChange={e => setHours(e.target.value)}/><div className="range-labels"><span>1 hr</span><span>8 hrs</span></div></div><div className="divider"/><div className="budget-control"><div className="control-label">Your budget</div><div className="budget-buttons">{['$', '$$', '$$$'].map(value => <button key={value} onClick={() => setBudget(value)} className={budget === value ? 'selected' : ''}>{value}</button>)}</div></div><div className="divider"/><div className="vibe-control"><div className="control-label">What’s your vibe?</div><div className="vibe-chips">{vibes.map(vibe => <button key={vibe} onClick={() => toggleVibe(vibe)} className={chosenVibes.includes(vibe) ? 'selected' : ''}>{chosenVibes.includes(vibe) && <Check size={13}/>} {vibe}</button>)}</div></div></section>
      <main className="content"><section className="discover"><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{rain ? 'A weather-proof adventure' : 'Your hidden gems nearby'}</h2></div><button className="text-button">See all gems <ArrowUpRight size={15}/></button></div><div className="feed-grid"><MapMock experiences={experiences}/><div className="cards-grid">{experiences.map((item, index) => <ExperienceCard key={item.id} item={item} index={index} inItinerary={itinerary.includes(item.id)} addToItinerary={addToItinerary}/>)}</div></div></section><Itinerary items={itineraryItems} used={totalMinutes} available={hours * 60}/></main>
    </> : <MerchantPortal/>}
  </div>;
}

function MapMock({experiences}) { return <div className="map-panel"><div className="map-header"><span><MapPin size={16}/> LIVE DISCOVERY MAP</span><button><Users size={15}/> 186 exploring nearby</button></div><div className="map-gridlines"/><div className="water water-a"/><div className="water water-b"/><span className="street s1">MERIDIAN ST</span><span className="street s2">SABLE AVE</span><span className="street s3">CATHEDRAL WAY</span>{experiences.map((item, i) => <div className={`pin pin-${i}`} key={item.id}><span>{item.pin}</span><div className="pin-label"><b>{item.match}% match</b><small>{item.title}</small></div></div>)}<div className="you-are-here"><span/><div><b>You are here</b><small>Downtown Quarter</small></div></div><div className="map-brand">HiddenGems<span>AI</span></div></div> }
function ExperienceCard({item, index, inItinerary, addToItinerary}) { return <article className="experience-card" style={{'--delay': `${index * 70}ms`}}><div className="card-image"><img src={item.image} alt={item.title}/><div className="auth-badge"><Star size={11} fill="currentColor"/> 95% authentic</div><button className="save"><Plus size={17}/></button></div><div className="card-body"><p className="category">{item.kind}</p><h3>{item.title}</h3><div className="meta"><span><MapPin size={13}/>{item.distance}</span><span><Clock3 size={13}/>{item.duration}</span></div><div className="fit"><div><span>AI feasibility</span><b>{item.fit}% fit</b></div><div className="progress"><i style={{width: `${item.fit}%`}}/></div></div><button className={inItinerary ? 'added action' : 'action'} onClick={() => addToItinerary(item.id)}>{inItinerary ? <><Check size={15}/> Added to route</> : <>Add to itinerary <Plus size={15}/></>}</button></div></article> }
function Itinerary({items, used, available}) { return <aside className="itinerary glass"><div className="itinerary-top"><div><p className="eyebrow"><Zap size={13}/> YOUR MICRO-ITINERARY</p><h2>Afternoon of small wonders</h2></div><button><ChevronDown size={18}/></button></div><div className="route-progress"><div><span>{Math.floor(used / 60)} hrs {used % 60} mins used</span><b>of {available / 60} hrs</b></div><div className="progress"><i style={{width: `${Math.min((used / available) * 100, 100)}%`}}/></div></div><div className="timeline">{items.map((item, index) => <div className="timeline-item" key={item.id}><div className="step"><span>{index + 1}</span>{index < items.length - 1 && <i/>}</div><div><p>{item.duration} · {item.travel}</p><h3>{item.title}</h3><small>{item.kind}</small></div></div>)}</div><div className="itinerary-footer"><div><span>Total value</span><b>${budgetValue(items)}</b></div><button>Book all & save <ArrowUpRight size={16}/></button></div></aside> }
const budgetValue = (items) => items.length ? items.length * 18 + 14 : 0;
function MerchantPortal(){ const [offer, setOffer] = useState({discount:'20', duration:'2 hours', vibe:'Local Artisans'}); const [sent, setSent] = useState(false); return <main className="merchant"><header className="merchant-hero"><p className="eyebrow"><Zap size={14}/> MERCHANT PORTAL</p><h1>Turn nearby intent into <em>footfall.</em></h1><p>Surface the right offer to travelers who are ready to discover something special.</p></header><section className="merchant-grid"><div className="footfall glass"><p className="eyebrow">RIGHT NOW, NEAR YOU</p><div className="footfall-title"><div className="pulse"><span/></div><div><h2>High traveler footfall</h2><p>Downtown Quarter · 500m radius</p></div></div><div className="metric-row"><div><b>186</b><span>active explorers</span></div><div><b>64%</b><span>seeking local picks</span></div><div><b>+28%</b><span>vs last hour</span></div></div><div className="activity-chart">{[31,48,39,65,58,82,72,94,86,100,89,96].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><form className="offer-form glass" onSubmit={e=>{e.preventDefault();setSent(true)}}><div><p className="eyebrow">MAKE AN OFFER</p><h2>Create a flash micro-offer</h2></div><label>Discount <div className="input-wrap"><input value={offer.discount} onChange={e=>setOffer({...offer,discount:e.target.value})}/><span>% OFF</span></div></label><label>Available for <select value={offer.duration} onChange={e=>setOffer({...offer,duration:e.target.value})}><option>1 hour</option><option>2 hours</option><option>Until closing</option></select></label><label>Target vibe <select value={offer.vibe} onChange={e=>setOffer({...offer,vibe:e.target.value})}>{vibes.map(x=><option key={x}>{x}</option>)}</select></label><button className={sent ? 'broadcast sent' : 'broadcast'} type="submit">{sent ? <><Check size={17}/> Broadcast live</> : <><Zap size={17}/> Broadcast to idle travelers</>}</button></form></section></main> }

createRoot(document.getElementById('root')).render(<App/>);
